-- CarouselFlow AI — ClickHouse Schema
-- Run: clickhouse-client --database carouselflow < database/schema.sql

CREATE DATABASE IF NOT EXISTS carouselflow;
USE carouselflow;

-- ── carousel_projects ─────────────────────────────────────────────
-- Each generation job / project
CREATE TABLE IF NOT EXISTS carousel_projects (
    id          String,
    topic       String,
    status      LowCardinality(String),  -- pending | running | done | error
    brand_id    String          DEFAULT '',
    style       String          DEFAULT '',
    slide_count UInt8           DEFAULT 6,
    created_at  DateTime        DEFAULT now(),
    completed_at Nullable(DateTime)
) ENGINE = ReplacingMergeTree()
ORDER BY (created_at, id);

-- ── agent_events ──────────────────────────────────────────────────
-- Real-time streaming events emitted by each agent stage
CREATE TABLE IF NOT EXISTS agent_events (
    project_id  String,
    agent_name  LowCardinality(String),  -- research | style_reference | brand | copywriting | carousel_engine
    event_type  LowCardinality(String),  -- start | thinking | tool_call | done | error
    content     String,
    sponsor     LowCardinality(String),  -- deepmind | clickhouse | datadog
    duration_ms UInt32          DEFAULT 0,
    tokens_used UInt32          DEFAULT 0,
    created_at  DateTime        DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (created_at, project_id, agent_name);

-- ── generated_slides ─────────────────────────────────────────────
-- Final carousel slides produced by the pipeline
CREATE TABLE IF NOT EXISTS generated_slides (
    project_id   String,
    slide_index  UInt8,
    title        String,
    body         String,
    image_prompt String          DEFAULT '',
    bg_color     String          DEFAULT '#0D0D0D',
    accent       String          DEFAULT '#4F6EF7',
    text_color   String          DEFAULT '#FFFFFF',
    font         String          DEFAULT 'Inter',
    created_at   DateTime        DEFAULT now()
) ENGINE = MergeTree()
ORDER BY (project_id, slide_index);

-- ── style_profiles ────────────────────────────────────────────────
-- Style references uploaded by users or generated by Style Reference Agent
CREATE TABLE IF NOT EXISTS style_profiles (
    name        String,
    palette     String,   -- JSON: { bg, accent, text, muted }
    typography  String,
    tone        String,
    created_at  DateTime  DEFAULT now()
) ENGINE = MergeTree()
ORDER BY created_at;

-- ── analytics_events ─────────────────────────────────────────────
-- User-facing analytics: page views, CTA clicks, generate events
CREATE TABLE IF NOT EXISTS analytics_events (
    event_name  LowCardinality(String),
    project_id  String          DEFAULT '',
    properties  String          DEFAULT '{}',  -- JSON
    created_at  DateTime        DEFAULT now()
) ENGINE = MergeTree()
ORDER BY created_at;
